### ISSUE TITLE
ImportError: No module named '_widget'

### ISSUE THREAD

**Issue by Cruzar** [jim-easterbrook/python-gphoto2#55]
Installed using pip3.

When running: 

> pi@raspberrypi:/usr/local/share/python-gphoto2/examples $ python3 camera-summary.py

I get the following error:

> pi@raspberrypi:/usr/local/share/python-gphoto2/examples $ python3 list-cameras.py
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/widget.py", line 28, in swig_import_helper
>     return importlib.import_module(mname)
>   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 577, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 914, in create_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
> ImportError: libgphoto2_port.so.10: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "list-cameras.py", line 25, in <module>
>     import gphoto2 as gp
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/__init__.py", line 17, in <module>
>     from gphoto2.abilities_list import *
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/abilities_list.py", line 9, in <module>
>     import gphoto2.camera
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/camera.py", line 10, in <module>
>     import gphoto2.context
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/context.py", line 11, in <module>
>     import gphoto2.file
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/file.py", line 12, in <module>
>     import gphoto2.filesys
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/filesys.py", line 13, in <module>
>     import gphoto2.list
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/list.py", line 14, in <module>
>     import gphoto2.port_info_list
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/port_info_list.py", line 15, in <module>
>     import gphoto2.port_log
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/port_log.py", line 16, in <module>
>     import gphoto2.result
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/result.py", line 17, in <module>
>     import gphoto2.version
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/version.py", line 18, in <module>
>     import gphoto2.widget
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/widget.py", line 31, in <module>
>     _widget = swig_import_helper()
>   File "/usr/local/lib/python3.5/dist-packages/gphoto2/widget.py", line 30, in swig_import_helper
>     return importlib.import_module('_widget')
>   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: No module named '_widget'

Have any idea of the reason?

**Comment by jim-easterbrook** [comment]
I suspect this is a similar problem to issue #48. How have you installed libgphoto2?

**Comment by jim-easterbrook** [comment]
The `ldd` output shows that `gphoto2` was compiled with `libgphoto2_port.so.12` but `python-gphoto2` was compiled (i.e. installed) with `libgphoto2_port.so.10`. The usual cure for this is to reinstall, as described in the README.
https://github.com/jim-easterbrook/python-gphoto2#reinstalling

The camera-summary error suggests your camera is not using utf-8 encoding for non-ASCII characters. You could try changing line 36 to
`print(text.text.decode('utf8','replace'))`

**Comment by jim-easterbrook** [comment]
I've found out a bit more about this "surrogate" thing. You should be able to retrieve the original bytes by using `text.text.encode('utf-8', errors='surrogateescape')`. See http://www.swig.org/Doc3.0/Python.html#Python_nn77 for more info.
